package:
  name: streamliner
  version: 1.2.0
  build:
    number: 0
    noarch: generic
source:
  path: .
requirements:
  build:
    - bash
  run:
    - bash
    - samtools
    - bc
    - coreutils
    - bedtools
    - pbtk
    - pbjasmine
    - pbmm2
    - pb-cpg-tools
    - ncbi-datasets-cli
    - yh1126::streamgc
    - yh1126::streambpb
test:
  commands:
    - streamliner --help
about:
  home: https://github.com/yh1126611/streamliner
  license: MIT
  summary: Streamline from assembly, annotation and raw reads to MP scores on specific sites
